implemented-interaction-external-api
n4x15/my-favourite-movies-api pull request #3
Opened 2022-04-01 07:57 UTC by n4x15

2022-04-01 10:12 UTC, Isidora25 requested changes

2022-04-01 10:12 UTC, Isidora25 commented on src/tmdbrequest/tmdbRequest.controller.ts
> +  @Get('genres')
А для чего эндпойнты эти? у тебя не будет гgraphql?

2022-04-01 10:12 UTC, Isidora25 commented on src/utils/utils.ts
> +export const effectiveUrl = (filters: GetMoviesArgs) => {
effective он конечно очень effective, но для всех урлов не подходит, используется только для урлов, с фильтрами
Так может переименовать, чтобы по названию было понятно вид урлов, с которым ты тут работаешь

2022-04-01 10:12 UTC, Isidora25 commented on src/utils/utils.ts
> +    page: 1,
Всегда только одну страницу будешь запрашивать?

2022-04-01 10:12 UTC, Isidora25 commented on src/utils/utils.ts
> +    page: 1,
Какой-то не очень богатый ассортимент получается

2022-04-01 10:12 UTC, Isidora25 commented on src/tmdbrequest/tmdbRequest.service.ts
> +        catchError(err => of([]))
Если честно, вообще не понимаю, что тут происходит 
Поймали ошибку и дальше что?

2022-04-01 10:12 UTC, Isidora25 commented on src/tmdbrequest/tmdbRequest.service.ts
> +  getMovies(filters: GetMoviesArgs) {
Что вернет этот метод? Какой у него возвращаемый тип?

2022-04-04 07:52 UTC, n4x15 commented on src/tmdbrequest/tmdbRequest.service.ts
> +        catchError(err => of([]))
Была мысль просто вернуть пустой массив при ошибке. Как лучше обработать ошибку?

2022-04-04 08:01 UTC, Isidora25 commented on src/tmdbrequest/tmdbRequest.service.ts
> +        catchError(err => of([]))
Нужно ее во-первых залогировать (https://docs.nestjs.com/techniques/logger), а во-вторых отправить юзеру сообщение об ошибке (https://docs.nestjs.com/exception-filters#throwing-standard-exceptions)

2022-04-04 10:03 UTC, Isidora25 commented on src/utils/utils.ts
> +
Теперь совсем пагинации не будет?

2022-04-04 10:05 UTC, Isidora25 approved these changes

2022-04-04 10:50 UTC, merged