feature-implemented-graphql
n4x15/my-favourite-movies-api pull request #4
Opened 2022-04-13 11:19 UTC by n4x15

2022-04-13 11:49 UTC, reshetov requested changes

2022-04-13 11:49 UTC, reshetov commented on src/migrations/1649247647143-updateGenres.ts
> +        await queryRunner.query(`ALTER TABLE "genres" ALTER COLUMN "isChecked" SET DEFAULT false`);
А зачем это поле. Если ты будешь хранить все жанры и отмечать кто из них checked а кто нет, то у тебя куча мусорных данных будет. Тут нужна следующая схема
User -> has many Genres (id, genreId, userId) т.е. ты хранишь в базе только выбранные жанры, а весь список по API получаешь

2022-04-13 11:49 UTC, reshetov commented on src/users/favoriteMovies/favoriteMovies.entity.ts
>  export class FavoriteMovies {
Может FavoriteMovie (это же один объект)

2022-04-13 11:49 UTC, reshetov commented on src/users/favoriteMovies/favoriteMovies.service.ts
> +    const userMoviesFromDB = await this.favoriteMoviesRepository.find({
Use relations (https://typeorm.io/relations) Luke!

2022-04-13 11:49 UTC, reshetov commented on src/users/favoriteMovies/favoriteMovies.service.ts
> +      !(await this.favoriteMoviesRepository.findOne({
Здесь и далее по коду я был стал использовать именно relations вместо того чтобы писать where{user} проще делать user.favoriteMovies и т.п.
НО - я точно не могу утверждать потому что в Nest я почти не играл, возможно я заблуждаюсь и так проще.
Спроси еще Таню, пусть она подскажет как у них на проекте

2022-04-18 10:23 UTC, reshetov approved these changes

2022-04-18 11:40 UTC, Isidora25 requested changes

2022-04-18 11:40 UTC, Isidora25 commented on src/tmdbrequest/dto/movie.dto.ts
> +  @Field()
Никакого snake_case, пожалуйста
Чтобы интегрироваться с внешним апи и при этом сохранить подход именования из js используй своство name в опциях Field декоратора

2022-04-18 11:40 UTC, Isidora25 commented on src/tmdbrequest/dto/movie.dto.ts
> +  @Field({defaultValue: false})
Проверь форматтер, нет пробелов после скобок

2022-04-18 11:40 UTC, Isidora25 commented on src/users/favoriteMovies/favoriteMovies.resolver.ts
> +    return this.favoriteMoviesService.getUserMovies(user.login);
Используй деструктуризацию для `login`

2022-04-18 11:40 UTC, Isidora25 commented on src/users/favoriteMovies/favoriteMovies.service.ts
> +        favoriteId: id,
А нельзя тут сразу юзера присоединить, при создании?

2022-04-18 11:40 UTC, Isidora25 commented on src/users/favoriteMovies/favoriteMovies.service.ts
> +    if (!movieExist) {
А если фильм существует, что вернется на фронт?

2022-04-18 11:40 UTC, Isidora25 commented on src/users/favoriteMovies/favoriteMovies.service.ts
> +    user.favoriteMovies = user.favoriteMovies.filter(
А что будет с удаляемым фильмом в таблице фильмов?

2022-04-18 11:40 UTC, Isidora25 commented on src/users/favoriteMovies/favoriteMovies.service.ts
> +    );
для того чтобы поставить одному объекту одно свойство в true не нужно перебирать все фильмы
а если у тебя их будет очень много?

2022-04-18 11:40 UTC, Isidora25 commented on src/users/genres/genres.service.ts
> +    const user = await this.userService.getUser(login);
используй деструктуризацию и тогда сервис сведется к одной строке

2022-04-18 11:40 UTC, Isidora25 commented on src/users/genres/genres.service.ts
> +      return this.userRepository.save(user);
Что вернется, если жанр будет существовать?

2022-04-18 11:40 UTC, Isidora25 commented on src/users/user.service.ts
> +    let user = await this.getUser(login);
А если юзер есть и вводит неправильный пароль?

2022-04-18 11:40 UTC, Isidora25 commented on src/users/user.service.ts
> +      user = await this.createUser(login, password);
прям так и положешь пароль в базу? 
плохо так делать, плохо

2022-04-18 11:40 UTC, Isidora25 commented on src/users/user.service.ts
> +    const jwt = require('jsonwebtoken');
А чего не импорт? И почему в сервисе?

2022-04-18 11:40 UTC, Isidora25 commented on src/users/authguard/auth.guard.ts
> +export class AuthGuard implements CanActivate {
У  nestjs есть отличный пример реализации аутентификации для graphQL 
и пример гарда там тоже есть 
https://docs.nestjs.com/security/authentication#graphql

2022-04-21 08:40 UTC, Isidora25 approved these changes

2022-04-21 09:35 UTC, reshetov approved these changes

2022-04-21 09:35 UTC, merged